-- =====================================================
-- ENABLE VECTOR EXTENSION
-- =====================================================

create extension if not exists vector;

-- =====================================================
-- DOCUMENTS TABLE (RAG)
-- =====================================================

create table if not exists documents (
  id bigserial primary key,
  content text not null,
  metadata jsonb default '{}'::jsonb,
  embedding vector(384),
  created_at timestamp default now()
);

create index if not exists documents_embedding_idx
on documents
using ivfflat (embedding vector_cosine_ops)
with (lists = 100);

-- =====================================================
-- MATCH DOCUMENTS FUNCTION (RAG SEARCH)
-- =====================================================

create or replace function match_documents (
  query_embedding vector(384),
  match_threshold float default 0.7,
  match_count int default 4
)
returns table (
  id bigint,
  content text,
  metadata jsonb,
  similarity float
)
language plpgsql
as $$
begin
  return query
  select
    d.id,
    d.content,
    d.metadata,
    1 - (d.embedding <=> query_embedding) as similarity
  from documents d
  where 1 - (d.embedding <=> query_embedding) > match_threshold
  order by d.embedding <=> query_embedding
  limit match_count;
end;
$$;

-- =====================================================
-- PROFILES TABLE (USER CONTEXT)
-- =====================================================

create table if not exists public.profiles (
  id uuid references auth.users not null primary key,
  age integer,
  medical_history text,
  allergies text,
  full_name text,
  created_at timestamp default now()
);

-- =====================================================
-- MEDICINES TABLE
-- =====================================================

create table if not exists public.medicines (
  id bigint generated by default as identity primary key,
  name text unique not null,
  description text,
  dosage_form text,
  price numeric,
  requires_prescription boolean default false,
  stock_quantity integer default 0,
  created_at timestamp default now()
);

create index if not exists medicines_name_idx on public.medicines (name);

-- =====================================================
-- DOCTORS TABLE
-- =====================================================

create table if not exists public.doctors (
  id bigint generated by default as identity primary key,
  name text not null,
  specialization text,
  consultation_fee numeric,
  availability text,
  rating numeric default 0,
  created_at timestamp default now()
);

create index if not exists doctors_specialization_idx
on public.doctors (specialization);

-- =====================================================
-- CONVERSATIONS TABLE (LONG-TERM MEMORY)
-- Stores every individual message per session
-- =====================================================

create table if not exists public.conversations (
  id bigserial primary key,
  session_id text not null,           -- unique ID per chat session
  role text not null,                  -- 'user' or 'assistant'
  content text not null,               -- message text
  intent text,                         -- router intent for this message
  created_at timestamp default now()
);

create index if not exists conversations_session_idx
on public.conversations (session_id);

create index if not exists conversations_created_idx
on public.conversations (created_at);

-- =====================================================
-- CONVERSATION SUMMARIES TABLE (LONG-TERM MEMORY)
-- Stores rolling summaries every N messages
-- =====================================================

create table if not exists public.conversation_summaries (
  id bigserial primary key,
  session_id text not null unique,     -- one summary per session (upserted)
  summary text not null,               -- LLM-generated rolling summary
  message_count integer default 0,     -- how many messages were summarized
  updated_at timestamp default now()
);

create index if not exists summaries_session_idx
on public.conversation_summaries (session_id);

-- =====================================================
-- SAMPLE MEDICINES DATA
-- =====================================================

insert into public.medicines
(name, description, dosage_form, price, requires_prescription, stock_quantity)
values
('Paracetamol',    'Pain reliever and fever reducer.',                     'Tablet',  5.00, false, 500),
('Ibuprofen',      'Nonsteroidal anti-inflammatory drug (NSAID).',         'Tablet',  8.00, false, 400),
('Amoxicillin',    'Antibiotic used to treat bacterial infections.',       'Capsule',15.00, true,  300),
('Cetirizine',     'Antihistamine used to relieve allergy symptoms.',      'Tablet',  4.00, false, 450),
('Aspirin',        'Pain reliever, fever reducer, and anti-inflammatory.', 'Tablet',  6.00, false, 350)
on conflict (name) do nothing;

-- =====================================================
-- SAMPLE DOCTORS DATA
-- =====================================================

insert into public.doctors
(name, specialization, consultation_fee, availability, rating)
values
('Dr. Smith', 'Cardiologist',        150.00, 'Mon-Wed 09:00-13:00', 4.8),
('Dr. Jones', 'Pediatrician',        100.00, 'Tue-Fri 10:00-16:00', 4.8),
('Dr. Brown', 'General Practitioner', 80.00, 'Mon-Fri 08:00-17:00', 4.6);